//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ImageProcess.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_IMAGEPROCESS_DIALOG         102
#define IDD_DIALOGImageFilter           103
#define IDD_DIALOGImageEnhance          104
#define IDD_DIALOGGeoTransform          105
#define IDR_MAINFRAME                   128
#define IDD_DIALOGEdgeDetect            140
#define IDD_DIALOGPreProcess1           142
#define IDD_DIALOGPreProcess2           144
#define IDD_DIALOGImageSharpen          146
#define IDC_ShowOriImg                  1000
#define IDC_BUTTONOpenImage             1002
#define IDC_ShowMidImage1               1004
#define IDC_ShowMidImage2               1005
#define IDC_BUTTONSaveImage             1006
#define IDC_ImageEnhance                1017
#define IDC_LineEnhance                 1018
#define IDC_BUTTONLineEnhance           1019
#define IDC_STATICK                     1020
#define IDC_STATICB                     1021
#define IDC_EquHist                     1024
#define IDC_BUTTONEquHist               1025
#define IDC_GammaEnhance                1026
#define IDC_LogEnhance                  1029
#define IDC_SegLineEnhance              1030
#define IDC_CLAHEEnhance                1031
#define IDC_STATICLogC                  1032
#define IDC_BUTTONLogEnhance            1034
#define IDC_STATISegLineK1              1035
#define IDC_STATISegLineK2              1036
#define IDC_STATISegLineB1              1039
#define IDC_STATISegLineB2              1041
#define IDC_BUTTONSegLine               1043
#define IDC_STATISegLineGray1           1044
#define IDC_STATISegLineGray2           1046
#define IDC_STATICContrastTh            1048
#define IDC_STATICGrid                  1049
#define IDC_BUTTONCRATE                 1052
#define IDC_BUTTONCLAHE                 1052
#define IDC_BUTTONBoxFilter             1053
#define IDC_BUTTONEdgeDetect            1053
#define IDC_BUTTONMeanFilter            1054
#define IDC_STATICCanny                 1054
#define IDC_BUTTONMedianFilter          1055
#define IDC_BUTTONCanny                 1055
#define IDC_BUTTONGaussianFilter        1056
#define IDC_STATICLowThresh             1056
#define IDC_BUTTONBilateralFilter       1057
#define IDC_EDITCannyLowThresh          1057
#define IDC_STATICHighThresh            1058
#define IDC_STATICPreProcess1           1058
#define IDC_STATICPreProcess            1058
#define IDC_EDITCannyHighThresh         1059
#define IDC_BUTTONPreProcess1           1059
#define IDC_BUTTONImageFilter1          1060
#define IDC_BUTTONImageEnhance1         1061
#define IDC_BUTTONImageFlip             1066
#define IDC_BUTTONImageRotate           1067
#define IDC_COMBOBoxFilter              1067
#define IDC_BUTTONImageMove             1068
#define IDC_COMBOMeanFilter             1068
#define IDC_BUTTONImageScale            1069
#define IDC_BUTTONAdjustFilter1         1069
#define IDC_COMBOMedianFilter           1069
#define IDC_BUTTONImageSimilarity       1070
#define IDC_BUTTONEnhanceAdjust1        1070
#define IDC_BUTTONImagePerpective       1071
#define IDC_COMBOGaussianFilterKernel   1071
#define IDC_COMBOGaussianFilterSigmaX   1072
#define IDC_COMBOGaussianFilterSigmaY   1073
#define IDC_COMBOBilateralFilterD       1074
#define IDC_COMBOBilateralFilterColor   1075
#define IDC_COMBOBilateralFilterLocate  1076
#define IDC_BUTTONPreProcess2           1077
#define IDC_BUTTONGeoTransform2         1078
#define IDC_BUTTONImageEnhance2         1079
#define IDC_COMBOImageMoveX             1081
#define IDC_SLIDERSmall                 1082
#define IDC_COMBOImageMoveY             1082
#define IDC_SLIDERBig                   1083
#define IDC_COMBOImageRotateAngle       1083
#define IDC_BUTTONImageFilter           1084
#define IDC_COMBOImageScale             1084
#define IDC_BUTTONImageEnhance          1085
#define IDC_COMBOImageSimilarityAngle   1085
#define IDC_BUTTONImageGeoTransform     1086
#define IDC_COMBO6                      1086
#define IDC_COMBOImageSimilarityScale   1086
#define IDC_COMBOGrid                   1086
#define IDC_BUTTONImageGray             1087
#define IDC_COMBOK                      1087
#define IDC_BUTTONBinary                1088
#define IDC_COMBOB                      1088
#define IDC_EDITBinaryMin               1089
#define IDC_COMBOCofficient             1089
#define IDC_EDITBinaryMax               1090
#define IDC_COMBOIndex                  1090
#define IDC_STATICBinary                1091
#define IDC_COMBOContrastThresh         1091
#define IDC_STATICBinaryMin             1092
#define IDC_COMBOLogC                   1092
#define IDC_STATICBinaryMax             1093
#define IDC_COMBOSegLineK1              1093
#define IDC_STATICBoxKernel             1094
#define IDC_COMBOSegLineB1              1094
#define IDC_STATICImageFlip             1094
#define IDC_STATICBoxFilter             1095
#define IDC_COMBOSegLineGray1           1095
#define IDC_COMBOImageFlip              1095
#define IDC_STATICMeanFilter            1096
#define IDC_COMBOSegLineK3              1096
#define IDC_COMBOSegLineK2              1096
#define IDC_STATICMeanKernel            1097
#define IDC_COMBOSegLineB2              1097
#define IDC_STATICAffine                1097
#define IDC_STATICMedianFilter          1098
#define IDC_COMBOSegLineGray2           1098
#define IDC_BUTTONImageAffine           1098
#define IDC_STATICMedianKernel          1099
#define IDC_BUTTONImageSharpen          1099
#define IDC_STATICGaussianFilter        1100
#define IDC_STATICSobel                 1100
#define IDC_STATICGaussianKernel        1101
#define IDC_STATICSobelKernel           1101
#define IDC_STATICBilateralFilter       1102
#define IDC_COMBOSobelKernel            1102
#define IDC_STATICBilateralD            1103
#define IDC_STATICSobelScale            1103
#define IDC_STATICGaussianKernelSigmaX  1104
#define IDC_COMBOSobelScale             1104
#define IDC_STATICGaussianKernelSigmaY  1105
#define IDC_STATICSobelDelta            1105
#define IDC_STATICBilateralSigmaColor   1106
#define IDC_COMBOSobelDelta             1106
#define IDC_STATICBilateralSigmaLocate  1107
#define IDC_BUTTONSobel                 1107
#define IDC_ImageFlip                   1108
#define IDC_STATICXorY                  1108
#define IDC_STATICFlip                  1109
#define IDC_COMBOXorY                   1109
#define IDC_ImageRotate                 1110
#define IDC_STATICLaplacian             1110
#define IDC_STATICRotate                1111
#define IDC_COMBOLapKernel              1111
#define IDC_ImageMove                   1112
#define IDC_BUTTONLaplacian             1112
#define IDC_STATICMoveX                 1113
#define IDC_BUTTONNextImage             1113
#define IDC_STATICMoveY                 1114
#define IDC_ImageScale                  1115
#define IDC_BUTTONPreImage              1115
#define IDC_STATICScale                 1116
#define IDC_BUTTONAdjustGeotransform    1116
#define IDC_ImageSimilarity             1117
#define IDC_BUTTONAdjustImageEnhance    1117
#define IDC_STATICScaleAngle            1118
#define IDC_BUTTONUndo                  1118
#define IDC_BUTTONRevoke                1118
#define IDC_STATICSimScale              1119
#define IDC_ImagePerspective            1120
#define IDC_BUTTONLineEnhance2          32813
#define IDC_BUTTONGammaEnhance          32813

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1119
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
